default:
  suites:
    default:
      type: symfony_bundle
      bundle: 'ZenIgrooveBundle'
  extensions:
      Behat\Symfony2Extension: ~
      Behat\MinkExtension:
            default_session: 'symfony2'
            base_url: 'http://localhost'
            sessions:
                symfony2:
                    symfony2: ~


