imag_ldap:
    resource: "@IMAGLdapBundle/Resources/config/routing.yml"
ZenIgrooveBundle:
    resource: "@ZenIgrooveBundle/Controller/"
    type:     annotation
    prefix:   /
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin