security:
  firewalls:
    dev:
      pattern:  ^/(_(profiler|wdt)|css|images|js|fonts)/
      security: false
    passwordChange:
      pattern:  ^/passwordChange/
      security: false
    restricted_area:
      pattern:          ^/
      anonymous:        ~
      provider:         ldap
      imag_ldap:        ~
      form_login:
          failure_handler:    zen.igroove.forcePasswordChangeAuthenticationFailureHandler
      logout:
        path:           /logout
        target:         /

  providers:
    ldap:
      id: imag_ldap.security.user.provider

  encoders:
    IMAG\LdapBundle\User\LdapUser: plaintext

  access_control:
    - { path: ^/checkGuest,     roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/login,          roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/admin,          roles: ROLE_ADMIN }
    - { path: ^/,               roles: IS_AUTHENTICATED_FULLY }

#  factories:
#    - "%kernel.root_dir%/../vendor/bundles/IMAG/LdapBundle/Resources/config/security_factories.xml"

  role_hierarchy:
        ROLE_ADMIN: [ROLE_RECEPTION, ROLE_TEACHER, ROLE_SONATA_ADMIN]
